"""empty message

Revision ID: 03c7dd8d6d30
Revises: d749ab8608bc
Create Date: 2023-08-15 12:00:29.166593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03c7dd8d6d30'
down_revision = 'd749ab8608bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_key', schema=None) as batch_op:
        batch_op.drop_column('domain')

    # ### end Alembic commands ###
