"""empty message

Revision ID: 24e5d8b0ac6e
Revises: a642dd0ed20f
Create Date: 2023-07-19 17:40:39.411363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24e5d8b0ac6e'
down_revision = 'a642dd0ed20f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_modified', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_column('date_modified')

    # ### end Alembic commands ###
