"""empty message

Revision ID: 46c741e2a968
Revises: d1459fab8702
Create Date: 2023-08-02 20:12:27.929660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46c741e2a968'
down_revision = 'd1459fab8702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    update_sql = '''
            UPDATE policy SET device_id = (
                SELECT m.device_id FROM policy_device_map m WHERE policy_id = policy.id
            )
        '''
    connection = op.get_bind()
    connection.execute(sa.text(update_sql))
    connection.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
