"""empty message

Revision ID: 8b1036aca862
Revises: b2250f184be8
Create Date: 2023-06-16 10:34:56.435562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1036aca862'
down_revision = 'b2250f184be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_config_valid_to'), ['valid_to'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_config_valid_to'))

    # ### end Alembic commands ###
