"""empty message

Revision ID: d1459fab8702
Revises: f31dc5799073
Create Date: 2023-07-30 16:45:02.350739

"""
import logging
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1459fab8702'
down_revision = 'f31dc5799073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    logger = logging.getLogger("alembic")
    logger.info("Starting migration d1459fab8702")

    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.Integer, nullable=True))
        batch_op.create_foreign_key("fk_policy_device_id_device", 'device', ['device_id'], ['id'])
        logger.info("Added device_id column to policy table")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    naming_convention = {
        "fk":
            "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }

    with op.batch_alter_table('policy', naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint("fk_policy_device_id_device", type_='foreignkey')
        batch_op.drop_column('device_id')

    # ### end Alembic commands ###
