"""empty message

Revision ID: d749ab8608bc
Revises: cdd8611f8f30
Create Date: 2023-08-09 13:56:15.891664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd749ab8608bc'
down_revision = 'cdd8611f8f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user_api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ext_system', sa.Uuid(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_api_key', schema=None) as batch_op:
        batch_op.drop_column('ext_system')

    with op.batch_alter_table('policy', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
