"""empty message

Revision ID: f31dc5799073
Revises: 24e5d8b0ac6e
Create Date: 2023-07-23 11:32:04.027617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31dc5799073'
down_revision = '24e5d8b0ac6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source', sa.Uuid(), nullable=False),
    sa.Column('interval_start', sa.DateTime(), nullable=False),
    sa.Column('interval_end', sa.DateTime(), nullable=False),
    sa.Column('total_queries', sa.Integer(), nullable=False),
    sa.Column('unique_domains', sa.Integer(), nullable=False),
    sa.Column('queries_blocked', sa.Integer(), nullable=False),
    sa.Column('evt_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monitoring_report_data_source'), ['data_source'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monitoring_report_data_source'))

    op.drop_table('monitoring_report')
    # ### end Alembic commands ###
